-- MineboomApps alpha catalog. Add new user applications here.
-- file is relative to the repository root. System apps belong in MineboomOS.
return {
    {
        id          = "factory",
        name        = "Factory",
        description = "Legacy factory control mirror; not portable yet",
        status      = "legacy",
        version     = "2.0",
        category    = "automation",
        icon        = "Fa",
        iconBg      = colors.orange,
        iconFg      = colors.black,
        file        = "apps/factory.lua",
    },
    {
        id          = "storage",
        name        = "RS Store",
        description = "Legacy RS storage dashboard; not portable yet",
        status      = "legacy",
        version     = "2.0",
        category    = "automation",
        icon        = "RS",
        iconBg      = colors.cyan,
        iconFg      = colors.black,
        file        = "apps/storage.lua",
        devFile     = "apps/storage.dev.lua",
        devVersion  = "2.0-dev",
    },
    {
        id          = "rtc",
        name        = "RTC - RS to chest",
        description = "Pulls Material Checklist items from RS into a chest or buffer",
        status      = "alpha",
        version     = "1.23",
        category    = "automation",
        icon        = "RT",
        iconBg      = colors.cyan,
        iconFg      = colors.black,
        file        = "apps/rtc.lua",
        devFile     = "apps/rtc.dev.lua",
        devVersion  = "1.23-dev",
    },
    {
        id          = "hub",
        name        = "Hub",
        description = "Legacy server hub monitor; not portable yet",
        status      = "legacy",
        version     = "2.0",
        category    = "network",
        icon        = "Hu",
        iconBg      = colors.blue,
        iconFg      = colors.white,
        file        = "apps/hub.lua",
        devFile     = "apps/hub.dev.lua",
        devVersion  = "2.0-dev",
    },

    {
        id          = "transformer_powergrid",
        name        = "Transformer (PowerGrid)",
        description = "PowerGrid transformer winding calculator (turns ratio for target voltage)",
        status      = "alpha",
        version     = "1.9",
        category    = "automation",
        icon        = "Tx",
        iconBg      = colors.orange,
        iconFg      = colors.black,
        file        = "apps/transformer_powergrid.lua",
        requiredMods = { "PowerGrid" },
    },
    {
        id          = "minesweeper",
        name        = "Minesweeper",
        description = "Classic mines game with touch open/flag mode",
        status      = "alpha",
        version     = "1.3",
        category    = "games",
        icon        = "MS",
        iconBg      = colors.green,
        iconFg      = colors.white,
        file        = "apps/minesweeper.lua",
    },
    {
        id          = "snake",
        name        = "Snake",
        description = "Classic snake game with touch controls and saved best scores",
        status      = "alpha",
        version     = "1.1",
        category    = "games",
        icon        = "Sn",
        iconBg      = colors.lime,
        iconFg      = colors.black,
        file        = "apps/snake.lua",
    },
    {
        id          = "2048",
        name        = "2048",
        description = "Classic 2048 sliding tile puzzle with saved best score",
        status      = "alpha",
        version     = "2.1",
        category    = "games",
        icon        = "20",
        iconBg      = colors.yellow,
        iconFg      = colors.black,
        file        = "apps/2048.lua",
    },
    {
        id          = "skyraid",
        name        = "Sky Raid",
        description = "Vertical shoot 'em up: dodge bullet patterns, clear waves, fight bosses",
        status      = "alpha",
        version     = "1.0",
        category    = "games",
        icon        = "SR",
        iconBg      = colors.lightBlue,
        iconFg      = colors.black,
        file        = "apps/skyraid.lua",
    },
    {
        id          = "tetris",
        name        = "Tetris",
        description = "Falling blocks with next preview, ghost drop and saved best scores",
        status      = "alpha",
        version     = "1.0",
        category    = "games",
        icon        = "Tt",
        iconBg      = colors.cyan,
        iconFg      = colors.black,
        file        = "apps/tetris.lua",
    },
}
